version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb+srv://nguyenphuongvinh49_db_user:abc_123@cluster0.egrkmta.mongodb.net/FoodFast?retryWrites=true&w=majority&appName=Cluster0
      - KEY=eee9bfece0d5ea2f2ca39ef406564c15
      - CLOUDINARY_CLOUD_NAME=dc1vbmwvf
      - CLOUDINARY_API_KEY=154889875917397
      - CLOUDINARY_API_SECRET=2Hy_QeL-h-48cEQUSJhy7-3wM2k
      - MAPQUEST_API_KEY=6n8mOkjIr008hDT2QOx9Vs9NNsAmCWEz
      - STRIPE_SECRET_KEY=sk_test_26PHem9AhJZvU623DfE1x4sd
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: