apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://nguyenphuongvinh49_db_user:abc_123@cluster0.egrkmta.mongodb.net/FoodFast"
  KEY: "eee9bfece0d5ea2f2ca39ef406564c15"
  CLOUDINARY_API_SECRET: "2Hy_QeL-h-48cEQUSJhy7-3wM2k"
  STRIPE_SECRET_KEY: "sk_test_26PHem9AhJZvU623DfE1x4sd"