apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: "3000"
  CLOUDINARY_CLOUD_NAME: "dc1vbmwvf"
  CLOUDINARY_API_KEY: "154889875917397"
  MAPQUEST_API_KEY: "6n8mOkjIr008hDT2QOx9Vs9NNsAmCWEz"